services:
  - type: web
    name: eiwitlimonade-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # sleutel wordt ingesteld via het Render-dashboard, NIET in deze file
