services:
  - type: web
    name: eiwitlimonade-chatbot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
      - key: SITEMAP_URL
      - key: LANGUAGE
      - key: PORT
